### ISSUE TITLE
forego download link is broken

### ISSUE THREAD

**Issue by jeff303** [mik-laj/presto-kerberos-docker#22]
It seems that the binary download of `forego-stable-linux-amd64.tgz` (from the `Dockerfile`) is gone, because the hosting platform [shut down](https://equinox.io/blog/shutting-down).  To keep the Docker build working, we will need to find a new way to source this.  A similar issue seems to be faced by other projects (see, ex, ceph/ceph-container#1948).

**Comment by mik-laj** [comment]
Updated link. https://github.com/mik-laj/presto-kerberos-docker/pull/25/files
Thanks for reporting this issue.
